### ISSUE TITLE
Feature Request: Elven Accuracy/Triple ADV

### ISSUE THREAD

**Issue by PanoramicPanda** [JasonCostanza/Dice-Vault#18]
5e has a mechanic from a Feat known as Elven Accuracy, which for all intents and purposes turns Advantage into Roll 3d20 take the highest.

Would be nice to have supported.

**Comment by JasonCostanza** [comment]
Good to know. Our intent was to keep agnostic of game systems but perhaps we can capture this without binding ourselves too much to 5e terminology or specific feats. I saw you had similar feature requests for advantage so maybe we can solve both in 1 improvement somehow.

**Comment by PanoramicPanda** [comment]
I mean, Adv/Dis system is 5e terminology technically, but I get the want.

An alternative would be "Best of 2/Worst of 2" to be more agnostic. In which case Best of 3. Which makes me feel like it should be a counter so you could theoretically roll Best of 6.... but that's harder to catch on the button as per #19
