### ISSUE TITLE
Feature Request: Adv/Dis/Elven Accuracy Buttons on Normal Saved Rolls

### ISSUE THREAD

**Issue by PanoramicPanda** [JasonCostanza/Dice-Vault#19]
**Is your feature request related to a problem? Please describe.**
Saving 3 versions of a roll feels bad.

**Describe the solution you'd like**
When saving a normal roll, instead of just "Quick Roll", have buttons to also roll the different Adv states. Could also be a toggle when you save a roll so it's not on _every_ saved roll card. Or only include them on cards that are d20's.

**Describe alternatives you've considered**
Saving a roll 3 times.

**Comment by JasonCostanza** [comment]
Ah I see what you mean, instead of saving the advantage state have that as buttons alongside quick roll. I had made the observation that multiple saves of the same roll feels bad just hadn't had time to evaluate the right solve. We'll look at your idea as that very well may be the best option

**Comment by PanoramicPanda** [comment]
If you're open to contributions, I might be able to take a stab at it this weekend.
