### ISSUE TITLE
Feature Request: Modifier be a number box?

### ISSUE THREAD

**Issue by PanoramicPanda** [JasonCostanza/Dice-Vault#20]
**Is your feature request related to a problem? Please describe.**
I have a roll that has +17 modifier on it. Having to click 17 times feels bad.

**Describe the solution you'd like**
Modifier be a number box instead. Maybe with a +/- clickable above/below?

**Comment by JasonCostanza** [comment]
This is a very good point! I think this is definitely something we can look into.

**Comment by JasonCostanza** [comment]
@PanoramicPanda I think we should knock this one out _first_ and then we can design the other improvements around advantage, disadvantage, crits, and UI improvements together in a larger UX improvement. We have like 3 improvements that sort of overlap into a more notable redesign but this will plug into that first. What do you think? If you don't have time I can try to convert this over this weekend to a text input field

**Comment by JasonCostanza** [comment]
Another idea, what if we made this just respond to mouse wheel input? Click +/- 1 and mouse wheel +/- 1 very quickly

**Comment by PanoramicPanda** [comment]
That's not very intuitive for a user, unlike a number box.
