### ISSUE TITLE
Feature Request: Roll Groups

### ISSUE THREAD

**Issue by PanoramicPanda** [JasonCostanza/Dice-Vault#21]
**Is your feature request related to a problem? Please describe.**
When rolling something like an attack damage that does `2d6+5 slashing + 1d6 poison` I'd like a way to split those to report the two damages sepately, without having to save as two different rolls.

**Describe the solution you'd like**
This can be seen already supported by TaleSpire's dice URL scheme: `talespire://dice/Slashing:2d6+5/Poison:1d6`. I'm not sure how best to display it within the UI.

**Comment by JasonCostanza** [comment]
Indeed we should handle this. Lots of situations where damage is multiple types. Thank you for the reference! We'll look into adding dice group support. The UI part of this will be the toughest, we'll chew on this idea and how to capture it.

**Comment by PanoramicPanda** [comment]
Initial thought is the ability to add another row in the editing space (Via a + icon?), that goes between the Dice and the Roll Types. The row would have another label entry + another set of dice w/mod and the ability to add yet another row. When a roll is Reset or Saved, the additional roll groups would clear away.

Pros: Does exactly what it says on the tin. I feel it would be fairly intuitive.
Cons: Space intensive if you keep adding more roll groups to the roll.

**Comment by JasonCostanza** [comment]
I think it's definitely worth a branch we can all experiment on to see how bad the UI space is if we add 2-3 rows of dice damage types. We might have to make our roll cards a bit more advanced maybe even offering scrolling inside the card itself if the person has like some wicked 3-4 damage type rolls. That way we can preserve size of each row but not bloat the size of each card, nor make content so small it's impossible to read. I can try to draft some ideas visually this weekend unless you beat me to it feel free to stab at this.

**Comment by JasonCostanza** [comment]
Lunch time pondering on an idea to implement this
![image](https://github.com/JasonCostanza/Dice-Vault/assets/30665880/ecb5bfbb-da87-47c0-86bd-0ea35b22ae1b)

**Comment by JasonCostanza** [comment]
> Lunch time pondering on an idea to implement this ![image](https://private-user-images.githubusercontent.com/30665880/320628462-ecb5bfbb-da87-47c0-86bd-0ea35b22ae1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDU1MTYsIm5iZiI6MTcxMjYwNTIxNiwicGF0aCI6Ii8zMDY2NTg4MC8zMjA2Mjg0NjItZWNiNWJmYmItZGE4Ny00N2MwLTg2YmQtMGVhMzViMjJhZTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE5NDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZGZiZmM0ZWExZTNjYmM0YzI3ZTNhNzNiN2M1YzYyMDNkOGIzNjNlZDViZDJjMGU3OWFhNjg2YjU3NjJiZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7vh7uTY0Px9wYHWHlunS4AeIilDLXOF7WyMw5wwnmIk)

Note, to discard the roll in Talespire, user right clicks on the dice tray in-game.
The idea is that each new group added just adds to the existing roll, so we'd need to know the last roll sent, then add the amendment, then resend the roll to Talespire so it updates in-game.

Talespire Roll = `lastSentRoll` + `amendment`

**Comment by PanoramicPanda** [comment]
That would probably be _easier_ to implement than full groups per roll, but probably wouldn't feel as good. If I have a Flametongue Longsword for instance, _every_ attack I would have to then click my longsword damage + my fire damage add group.

**Comment by JasonCostanza** [comment]
Turns out this is rather difficult to implement. Now is when I wish I had taken more computer science courses in college or something. I have the UI at least mostly set up for the staged roll / group, may still tweak it, but we add a row of dice icons to configure the roll group and the reset button clears everything. What I want to do is when it's saved, we strip the dice icons and convert it to text to keep the saved items smaller. All this requires figuring out how to parse the rows into JSON which is where I'm currently slamming my head up against. All to say, this is taking a lot longer to figure out than I had hoped

**Comment by JasonCostanza** [comment]
Implemented in 2.0
