### ISSUE TITLE
Feature Request: Add "gmOnly" rolls

### ISSUE THREAD

**Issue by JasonCostanza** [JasonCostanza/Dice-Vault#6]
Looking at the rollEvent payload, there is a parameter for "GM Only" which is an interesting idea I haven't considered and apparently is supported

```rollEvent:  
{kind: 'rollResults', payload: {…}}
kind: "rollResults"
payload: {rollId: '64424509441', clientId: '5a8814ba-f4bb-4ddb-a453-e930162e62e1', resultsGroups: Array(1), gmOnly: false, quiet: false}
[[Prototype]]: Object```

**Comment by JasonCostanza** [comment]
@PanoramicPanda is this the correct idea, we can add a UI element to make the roll a secret "DM Only" roll so players at the table won't see the result in chat?

**Comment by JasonCostanza** [comment]
Oh I see! So we actually don't need to add any functionality here because if we wanted a GM roll, once we send to the tray we just drag out of the GM box from there which also natively covers hiding the results?

**Comment by PanoramicPanda** [comment]
Yes, this is automagically handled. In the screenshot below, you can see a gm dice roll and non-gm dice roll on the table, and the player only sees the non-gm result in the chat.

![image](https://github.com/JasonCostanza/Dice-Vault/assets/1569246/870ad2d2-4553-456c-bfb0-09f761c36ffe)
